import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { ProviderWrapper } from "@/provider/ProviderWrapper";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ProviderWrapper>
            <div className="flex flex-col min-h-screen">
              {/* Header */}
              <Header />

              {/* Main Content */}
              <main className="flex-1">{children}</main>
              <Toaster richColors />
              {/* Footer */}
              <Footer />
            </div>
            </ProviderWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
  // return (
  //   <ClerkProvider>
  //     <html lang="en" suppressHydrationWarning>
  //       <body
  //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //       >
  //         <ThemeProvider
  //           attribute="class"
  //           defaultTheme="system"
  //           enableSystem
  //           disableTransitionOnChange
  //         >
  //           <div className="flex flex-col min-h-screen">
  //             {/* Header */}
  //             <Header />

  //             {/* Main Content */}
  //             <main className="flex-1">{children}</main>

  //             {/* Footer */}
  //             <Footer />
  //           </div>
  //         </ThemeProvider>
  //       </body>
  //     </html>
  //   </ClerkProvider>
  // );
}
